---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Set .bashrc file
    copy:
      src: files/.bashrc
      dest: /home/cyfraka/.bashrc
      owner: cyfraka
      group: cyfraka

  - name: Set .vimrc
    copy:
      src: files/.vimrc
      dest: /home/cyfraka/.vimrc
      owner: cyfraka
      group: cyfraka      

  - name: install packages
    package:
      name: 
        - kitty
        - vim
        - neofetch
        - gnome-tweaks

  - name: copy wallpaper file
    copy:
      src: files/80s.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/background/pictures-uri"
      Value: "'zoom'"

- name: add ansible user
    user:
      name: angel
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_angel
      dest: /etc/sudoers.d/angel
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: angel
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Cyfraka/ansible.git

