---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - kitty
        - vim
        - neofetch
        - gnome-tweaks

  - name: copy wallpaper file
    copy:
      src: files/80s.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/background/pictures-uri"
      Value: "'zoom'"
