---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Set .bashrc file
    copy:
      src: files/.bashrc
      dest: /home/cyfraka/.bashrc
      owner: cyfraka
      group: cyfraka

  - name: Set .vimrc file
    copy:
      src: files/.vimrc
      dest: /home/cyfraka/.vimrc
      owner: cyfraka
      group: cyfraka      

  - name: Create Kitty directory
    file:
      path: /home/cyfraka/.config/kitty
      state: directory

  - name: Set Kitty .conf file
    copy:
      src: files/.config/kitty/kitty.conf
      dest: /home/cyfraka/.config/kitty/kitty.conf
      owner: cyfraka
      group: cyfraka

  - name: Install Packages
    package:
      name: 
        - kitty
        - vim
        - neofetch
        - gnome-tweaks
        - cronie
        - bpytop

  - name: Copy picture Cyfraka
    copy:
      src: files/Cyfraka.jpg
      dest: /home/cyfraka/Pictures/Cyfraka.jpg
      owner: cyfraka
      group: cyfraka

  - name: Copy picture 80s
    copy:
      src: files/80s.jpg
      dest: /home/cyfraka/Pictures/80s.jpg
      owner: cyfraka
      group: cyfraka

  - name: Copy Wallpaper file
    copy:
      src: files/80s.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: Set Wallpaper
    become_user: cyfraka
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: Add Ansible User
    user:
      name: angel
      system: yes

  - name: Set sudo for Ansible User
    copy:
      src: files/sudoer_angel
      dest: /etc/sudoers.d/angel
      owner: root
      group: root
      mode: 0440

  - name: Add Ansible-Pull Cron Job
    cron:
      name: ansible auto-provision
      user: angel
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Cyfraka/x230-Ansible.git

